import React, { useState } from 'react';
import { ChevronDown, ChevronUp, HelpCircle } from 'lucide-react';

const FAQ = () => {
  const [openIndex, setOpenIndex] = useState(null);

  const faqs = [
    {
      question: "What are crypto trading signals?",
      answer: "Crypto trading signals are expert recommendations that include specific entry points, target prices, and stop-loss levels for cryptocurrency trades. Our signals are generated by experienced traders using technical analysis, market trends, and proven strategies to help you make informed trading decisions."
    },
    {
      question: "How accurate are your signals?",
      answer: "We maintain a 95% accuracy rate on our premium signals. Our team of expert analysts uses advanced technical analysis, fundamental research, and market sentiment data to provide high-quality signals. However, cryptocurrency markets are volatile, and past performance doesn't guarantee future results. We always recommend proper risk management."
    },
    {
      question: "How do I receive the trading signals?",
      answer: "Once you subscribe to any of our plans, you'll get instant access to our premium Telegram/WhatsApp group where signals are posted in real-time. You'll receive notifications for new signals, market updates, and important announcements. Our signals include clear entry prices, target levels, and stop-loss points."
    },
    {
      question: "What's the difference between the free and premium channels?",
      answer: "The free channel provides basic market insights and occasional signals to help you get started. Premium channels offer daily high-quality signals, detailed market analysis, priority support, exclusive trading strategies, and access to our community of successful traders with higher profit potential."
    },
    {
      question: "Can I cancel my subscription anytime?",
      answer: "Yes, you have full control over your subscription. For monthly plans, you can cancel before the next billing cycle. For longer-term plans (3 months, yearly, or lifetime), the access period you've paid for will remain active. We also offer refunds within the first 7 days if you're not satisfied with our service."
    },
    {
      question: "Do I need trading experience to use your signals?",
      answer: "No prior experience is required! Our signals are designed to be easy to follow with clear instructions. We provide entry prices, target prices, and stop-loss levels, making it simple for beginners. Additionally, we offer educational content and community support to help you learn and improve your trading skills."
    },
    {
      question: "What cryptocurrencies do you provide signals for?",
      answer: "We cover major cryptocurrencies including Bitcoin (BTC), Ethereum (ETH), Ripple (XRP), Cardano (ADA), Solana (SOL), Polkadot (DOT), Dogecoin (DOGE), and many other altcoins. Our signals focus on liquid markets with good trading volumes to ensure you can enter and exit positions easily."
    },
    {
      question: "How much capital do I need to start?",
      answer: "You can start with as little as $100, though we recommend starting with at least $500-$1000 for better risk management and diversification. The key is to never invest more than you can afford to lose and to follow our recommended position sizing guidelines to protect your capital."
    },
    {
      question: "What are the payment methods available?",
      answer: "We accept various payment methods including cryptocurrency (BTC, ETH, USDT), credit/debit cards, and PayPal. All transactions are secure and encrypted. Once payment is confirmed, you'll receive immediate access to your chosen plan and premium group."
    },
    {
      question: "Do you provide customer support?",
      answer: "Yes! Premium members get priority support through our dedicated support channels. We're available to help with trading questions, technical issues, and general inquiries. Our response time is typically within a few hours, and we have a knowledgeable team ready to assist you."
    }
  ];

  const toggleFAQ = (index) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section id="faq" className="py-16 md:py-24 bg-white dark:bg-gray-800 relative overflow-hidden">
      <div className="absolute top-0 left-1/4 w-80 h-80 bg-green-400/5 rounded-full blur-3xl"></div>
      <div className="absolute bottom-0 right-1/4 w-80 h-80 bg-amber-400/5 rounded-full blur-3xl"></div>

      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        <div className="text-center mb-16">
          <div className="flex justify-center mb-4">
            <HelpCircle className="h-12 w-12 text-green-500" />
          </div>
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            <span className="text-gray-800 dark:text-gray-100">Frequently Asked </span>
            <span className="text-green-600 dark:text-green-400">Questions</span>
          </h2>
          <p className="text-lg text-gray-600 dark:text-gray-300 max-w-3xl mx-auto">
            Everything you need to know about our crypto trading signals and services
          </p>
        </div>

        <div className="space-y-4">
          {faqs.map((faq, index) => (
            <div
              key={index}
              className="bg-gray-50 dark:bg-gray-900 rounded-lg border border-gray-200 dark:border-gray-700 overflow-hidden transition-all duration-300 hover:shadow-md"
            >
              <button
                onClick={() => toggleFAQ(index)}
                className="w-full px-6 py-4 flex justify-between items-center text-left focus:outline-none group"
              >
                <span className="font-semibold text-gray-800 dark:text-gray-100 pr-4 group-hover:text-green-600 dark:group-hover:text-green-400 transition-colors">
                  {faq.question}
                </span>
                <span className="flex-shrink-0 text-green-600 dark:text-green-400">
                  {openIndex === index ? (
                    <ChevronUp className="h-5 w-5" />
                  ) : (
                    <ChevronDown className="h-5 w-5" />
                  )}
                </span>
              </button>

              <div
                className={`transition-all duration-300 ease-in-out ${
                  openIndex === index
                    ? 'max-h-96 opacity-100'
                    : 'max-h-0 opacity-0'
                } overflow-hidden`}
              >
                <div className="px-6 pb-4 text-gray-600 dark:text-gray-400 leading-relaxed">
                  {faq.answer}
                </div>
              </div>
            </div>
          ))}
        </div>

        <div className="mt-12 text-center">
          <p className="text-gray-600 dark:text-gray-400 mb-4">
            Still have questions? We're here to help!
          </p>
          <a
            href="mailto:therealcryptog.official@gmail.com"
            className="inline-block bg-gradient-to-r from-green-500 to-green-600 hover:from-green-600 hover:to-green-700 text-white px-6 py-3 rounded-md font-medium transition-all hover:shadow-lg"
          >
            Contact Support
          </a>
        </div>
      </div>
    </section>
  );
};

export default FAQ;
